### ISSUE TITLE
为什么vs2013配置的时候出问题呢？运行第二个的时候崩了？

### ISSUE THREAD

**Issue by roseboych** [zilongshanren/opengl-tutorials#7]

**Comment by andyque** [comment]
奔溃的错误 信息是什么呢？

**Comment by asvo** [comment]
你好，我在playground.cpp中对着教程的代码输入运行第二个绘制三角形的例子中也崩溃了。
  崩溃在创建顶点数组对象的时候：
   glBindVertexArray(VertexArrayID2);

  https://cloud.githubusercontent.com/assets/9391884/12671154/b6446774-c6a8-11e5-864e-762b7d7ee820.PNG
![gl_tur_01](https://cloud.githubusercontent.com/assets/9391884/12671154/b6446774-c6a8-11e5-864e-762b7d7ee820.PNG)
